config/routes.rb
# PAPERTRAIL (mentor) gebruiken voor errors heroku!!!!
# echt domijn kopen!
# Handleiding schrijven! 1 team verwisselen is (meestal) genoeg :)
# password is havenstraat
# Ik mag nu geen roeiers wissen die teams hebben en omgekeerd, dat wordt leuk:(
# En kan teams ook niet leegmaken...




# Controle:
# Bij een lege resource gaat de hele site op zijn gat??
# Controleren of alles is gedefineerd  zoals results die later showen in heats pagina!
# validates laat gedaan in modell en niet nagekeken!
# Gaan alle lastige dingen zoals results op alle (inclusief team) paginas goed?
# results 1.20 + 2.0 is soms 3.21111111
# Gaat rank uitrekenen bij meerdere heats netjes?
# alle links controleren, sterkte!
# controleren of je club.id hebt omgeschreven in .name
# Wat ik  met mentor heb gedaan op club edit pagina met blank?
# alle destroy warning msges wel netjes? ook pop up?
# !!! Velden mogen niet leeg zijn, creeerde net 20 boten :)   en sommige unqieness
#  OEf werken alle notices and errors?

# Wat niet hoeft
# Bij maken team   aantal rowers afhankelijk van type is nog een uitdaging (hoeft niet)
# Als laatste clubs/edit veranderen! (of wel goed zo? wel meer vrijheid voor admin!)
#!!!VRAGEN!!! invoeren boten, boat_ids e.d.apparte pagina admin (lastig met keuze menu!)(params verstuurd welke geedit moet worden, piece of cake!)
# JUST DO IT! Boattype category noemen!! DAT IS EEN BITCH EERST NIEUWE GENEREREN DAN OUDE VERWIJDEREN :(

# Later
# !! uitkijken dat navbar niet op elkaar stapeld dan is de helft niet te zien
# Wel heel cool een navbar die eerst op site zweeft en later onder main navbar plakt, zie bootswatsch
# opmaak:
# responsive
# Small text in h1 header weg bij responsive!











ZzvJeugdwedstrijden::Application.routes.draw do

  # Routes for about:
  root :to => 'about#index'
  get '/about', controller: 'about', action: 'index', as: 'about'

  # Routes for sessions:
  get '/sessions/new' => 'sessions#new', as: 'new_session'
  post '/sessions' => 'sessions#create', as: 'sessions'
  delete '/sessions' => 'sessions#destroy'

  # Routes for the Admin resource:
  # CREATE
  get '/admins/new', controller: 'admins', action: 'new', as: 'new_admin'
  post '/admins', controller: 'admins', action: 'create'

  # READ
  get '/admins', controller: 'admins', action: 'index', as: 'admins'
  get '/admins/:id', controller: 'admins', action: 'show', as: 'admin'

  # UPDATE
  get '/admins/:id/edit', controller: 'admins', action: 'edit', as: 'edit_admin'
  put '/admins/:id', controller: 'admins', action: 'update'

  # DELETE
  delete '/admins/:id', controller: 'admins', action: 'destroy'
  #------------------------------

  # Routes for the Team_classification resource:
  # CREATE
  get '/team_classifications/new', controller: 'team_classifications', action: 'new', as: 'new_team_classification'
  post '/team_classifications', controller: 'team_classifications', action: 'create'

  # READ
  get '/team_classifications', controller: 'team_classifications', action: 'index', as: 'team_classifications'
  get '/team_classifications/:id', controller: 'team_classifications', action: 'show', as: 'team_classification'

  # UPDATE
  get '/team_classifications/:id/edit', controller: 'team_classifications', action: 'edit', as: 'edit_team_classification'
  put '/team_classifications/:id', controller: 'team_classifications', action: 'update'

  # DELETE
  delete '/team_classifications/:id', controller: 'team_classifications', action: 'destroy'
  #------------------------------

  # Routes for the Result resource:
  get '/results/edit', controller: 'results', action: 'edit', as: 'edit_result'

  # CREATE
  get '/results/new', controller: 'results', action: 'new', as: 'new_result'
  post '/results', controller: 'results', action: 'create'

  # READ
  get '/results', controller: 'results', action: 'index', as: 'results'
  get '/results/:id', controller: 'results', action: 'show', as: 'result'

  # UPDATE

  put '/results/:id', controller: 'results', action: 'update'

  # DELETE
  delete '/results/:id', controller: 'results', action: 'destroy'
  #------------------------------

  # Routes for the Team resource:
  # CREATE
  get '/teams/new', controller: 'teams', action: 'new', as: 'new_team'
  post '/teams', controller: 'teams', action: 'create'

  # READ
  get '/teams', controller: 'teams', action: 'index', as: 'teams'
  get '/teams/:id', controller: 'teams', action: 'show', as: 'team'

  # UPDATE
  get '/teams/:id/edit', controller: 'teams', action: 'edit', as: 'edit_team'
  put '/teams/:id', controller: 'teams', action: 'update'

  # DELETE
  delete '/teams/:id', controller: 'teams', action: 'destroy'

  #------------------------------

  # Routes for the Rower_classification resource:
  # CREATE
  get '/rower_classifications/new', controller: 'rower_classifications', action: 'new', as: 'new_rower_classification'
  post '/rower_classifications', controller: 'rower_classifications', action: 'create'

  # READ
  get '/rower_classifications', controller: 'rower_classifications', action: 'index', as: 'rower_classifications'
  get '/rower_classifications/:id', controller: 'rower_classifications', action: 'show', as: 'rower_classification'

  # UPDATE
  get '/rower_classifications/:id/edit', controller: 'rower_classifications', action: 'edit', as: 'edit_rower_classification'
  put '/rower_classifications/:id', controller: 'rower_classifications', action: 'update'

  # DELETE
  delete '/rower_classifications/:id', controller: 'rower_classifications', action: 'destroy'
  #------------------------------

  # Routes for the Rower resource:
  # CREATE
  get '/rowers/new', controller: 'rowers', action: 'new', as: 'new_rower'
  post '/rowers', controller: 'rowers', action: 'create'

  # READ
  get '/rowers', controller: 'rowers', action: 'index', as: 'rowers'
  get '/rowers/:id', controller: 'rowers', action: 'show', as: 'rower'

  # UPDATE
  get '/rowers/:id/edit', controller: 'rowers', action: 'edit', as: 'edit_rower'
  put '/rowers/:id', controller: 'rowers', action: 'update'

  # DELETE
  delete '/rowers/:id', controller: 'rowers', action: 'destroy'
  #------------------------------
  # Routes for the Heat resource:

  get '/heats/edit', controller: 'heats', action: 'edit', as: 'edit_heat'


  # CREATE
  get '/heats/new', controller: 'heats', action: 'new', as: 'new_heat'
  post '/heats', controller: 'heats', action: 'create'

  # READ
  get '/heats', controller: 'heats', action: 'index', as: 'heats'
  get '/heats/:id', controller: 'heats', action: 'show', as: 'heat'

  # UPDATE
  put '/heats/:id', controller: 'heats', action: 'update'

  # DELETE
  delete '/heats/:id', controller: 'heats', action: 'destroy'
  #------------------------------
  # Routes for the Club resource:

  # Teams & Rowers
  get '/clubs/:id/teams', controller: 'clubs', action: 'teams', as: 'club_teams'
  get '/clubs/:id/rowers', controller: 'clubs', action: 'rowers', as: 'club_rowers'

  # CREATE
  get '/clubs/new', controller: 'clubs', action: 'new', as: 'new_club'
  post '/clubs', controller: 'clubs', action: 'create'

  # READ
  get '/clubs', controller: 'clubs', action: 'index', as: 'clubs'
  get '/clubs/:id', controller: 'clubs', action: 'show', as: 'club'

  # UPDATE
  get '/clubs/:id/edit', controller: 'clubs', action: 'edit', as: 'edit_club'
  put '/clubs/:id', controller: 'clubs', action: 'update'

  # DELETE
  delete '/clubs/:id', controller: 'clubs', action: 'destroy'
  #------------------------------

  # Routes for the Boat_type resource:
  # CREATE
  get '/boat_types/new', controller: 'boat_types', action: 'new', as: 'new_boat_type'
  post '/boat_types', controller: 'boat_types', action: 'create'

  # READ
  get '/boat_types', controller: 'boat_types', action: 'index', as: 'boat_types'
  get '/boat_types/:id', controller: 'boat_types', action: 'show', as: 'boat_type'

  # UPDATE
  get '/boat_types/:id/edit', controller: 'boat_types', action: 'edit', as: 'edit_boat_type'
  put '/boat_types/:id', controller: 'boat_types', action: 'update'

  # DELETE
  delete '/boat_types/:id', controller: 'boat_types', action: 'destroy'

  # Calculate Rankings
  get '/boat_types/:id/calculaterank', controller: 'boat_types', action: 'calculaterank', as: 'calculaterank'
  #------------------------------

  # Routes for the Boat resource:
  # CREATE
  get '/boats/new', controller: 'boats', action: 'new', as: 'new_boat'
  post '/boats', controller: 'boats', action: 'create'

  # READ
  get '/boats', controller: 'boats', action: 'index', as: 'boats'
  get '/boats/:id', controller: 'boats', action: 'show', as: 'boat'

  # UPDATE
  get '/boats/:id/edit', controller: 'boats', action: 'edit', as: 'edit_boat'
  put '/boats/:id', controller: 'boats', action: 'update'

  # DELETE
  delete '/boats/:id', controller: 'boats', action: 'destroy'
  #------------------------------
end

app/models/club.rb
class Club < ActiveRecord::Base
  has_many :teams
  has_many :rowers

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
before_filter :authorize_user, except: [:index, :teams, :rowers]

before_filter :clubs_with_teams_and_rowers?, only: [:destroy]


def clubs_with_teams_and_rowers?
        @club = Club.find_by_id(params[:id])
        @club.errors.add(:base, "Can not delete clubs with rowers and teams assigned") unless @club.teams.count == 0 && @club.rowers.count == 0
        unless @club.errors.blank?
          flash[:error] = @club.errors.full_messages
          redirect_to :back
        end

end




  def teams
    @heats = Heat.all.sort! { |a,b| a.name.to_i <=> b.name.to_i }
    @teams = Team.all
    @club = Club.find_by_id(params[:id])
    render 'teams/index'
  end

  def rowers
    @rowers = Rower.all
    @club = Club.find_by_id(params[:id])
    render 'rowers/index'
  end

  def index
    @clubs = Club.all
  end

  def create
    @club = Club.new
    @club.name = params[:name]

    if @club.save
      redirect_to :back, notice: "Club created successfully"
    else
      flash[:error] = @club.errors.full_messages
      redirect_to :back
    end
  end

  def edit
    @club = Club.find_by_id(params[:id])
  end

  def update
    @club = Club.find_by_id(params[:id])
    @club.name = params[:name]

    if @club.save
            redirect_to :back, notice: "Club updated successfully"
          else
      flash[:error] = @club.errors.full_messages
      redirect_to :back
    end
  end

  def destroy
    @club = Club.find_by_id(params[:id])
    @club.destroy
        redirect_to :back, notice: "Club removed successfully"
      end
end

app/views/clubs/edit.html.erb
<div class="page-header">
  <h1><%= @club.name %> <small>where do you belong to?</small></h1>
</div>

<div class="row">
  <div class="span12">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Editing <%= @club.name %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <%= form_tag(club_url(@club), method: 'put') do %>

            <%= label_tag :name %><br />
            <%= text_field_tag :name, @club.name %>

            <%= submit_tag "Update Club Name", :class => "btn btn-success" %>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="span5">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Step 1) New Rower</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <%= form_tag(rowers_url, method: 'post') do %>

            <%# 4.times do %>

            <%= label_tag :name %><br />
            <%= text_field_tag :name %>

            <%= label_tag :age %><br />
            <%= text_field_tag :age %><br>

            <%# end %>


            <%= hidden_field_tag :club_id, @club.id %>

            <%= submit_tag "Create Rower", :class => "btn btn-success" %>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Age</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
    <% @club.rowers.each do |rower| %>
      <tr>
        <td><%= rower.name %></td>
        <td><%= rower.age %></td>

        <td>
          <%= link_to 'Edit', edit_rower_url(rower), :class => "btn btn-warning" %>
        </td>
        <td>
          <%= link_to 'Destroy', rower_url(rower), method: 'delete', data: { confirm: "Do you really want to delete this rower?" }, :class => "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  </div>

  <div class="span7">
        <% unless @club.rowers.blank? %>
    <table class="table table-striped">
      <thead>
        <tr><th>Step 2) New Team</th></tr>
      </thead>
      <tbody>
        <tr>
          <td>

            <%= form_tag(teams_url, method: 'post') do %>


            <%= label_tag :name %><br />
            <%= text_field_tag :name %>

            <%= label_tag :boat_type_id %><br />
            <%= select_tag :boat_type_id, options_from_collection_for_select(BoatType.all, :id, :name) %>

            <%= hidden_field_tag :club_id, @club.id %>

            <%= submit_tag "Create Team", :class => "btn btn-success" %>

            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
    <% end %>

    <% unless @club.teams.blank? %>
    <table class="table table-striped">
      <thead>
        <tr><th>Step 3) Add rowers to team</th></tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <%= form_tag(rower_classifications_url, method: 'post') do %>

              <%= label_tag :team_id %><br />
              <%= select_tag(:team_id, options_from_collection_for_select(@club.teams.all, :id, :name)) %>

              <% 4.times do |i| %>
                <%= label_tag :rower_id %><br />
                <%= select_tag("rower_id_" + i.to_s, options_from_collection_for_select(@club.rowers.all, :id, :name), :include_blank => true) %>
              <% end %>

              <%= submit_tag "Add to team", :class => "btn btn-success" %>
            <% end %>
          </td>
        </tr>
     </tbody>
    </table>


    <table class="table table-striped">
      <thead>
        <tr>
          <th>Teams</th>
          <th colspan="4">Rowers</th>
        </tr>
      </thead>
      <tbody>
        <% @club.teams.each do |team| %>
          <tr>
            <td><%= link_to team.name, team_url(team) %></td>
            <td>
                <%= team.boat_type.name %>
            </td>
            <td>
              <% team.rowers.each do |rower| %>
                <%= rower.name %>
              <% end %>
            </td>
            <td>
              <%= link_to 'Edit', edit_team_url(team), :class => "btn btn-warning" %>
            </td>
            <td>
              <%= link_to 'Destroy', team_url(team), method: 'delete', data: { confirm: "Do you really want to delete this team?" }, :class => "btn btn-danger" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <% end %>
  </div>
</div>

app/views/clubs/index.html.erb
<div class="page-header">
  <h1>Clubs <small>where do you belong to?</small></h1>
</div>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Number of Teams</th>
      <th></th>
      <th>Number of Rowers</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
  </thead>

  <tbody>
  <% @clubs.each do |club| %>
    <tr>
      <td><%= club.name %></td>
      <td><%= club.teams.count %></td>
      <td>
        <%= link_to 'Show Teams', club_teams_url(club), :class => "btn btn-inverse"  %>
      </td>
      <td><%= club.rowers.count %></td>
      <td>
        <%= link_to 'Show Rowers', club_rowers_url(club), :class => "btn btn-inverse"  %>
      </td>
      <% if signed_in? %>
      <td>
        <%= link_to 'Edit Club', edit_club_url(club), :class => "btn btn-success"  %>
      </td>
      <td>
        <%= link_to 'Destroy', club_url(club), method: 'delete', data: { confirm: "Do you really want to delete this club?" }, :class => "btn btn-warning" %>
      </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>