config/routes.rb
# PAPERTRAIL (mentor) gebruiken voor errors heroku!!!!
# echt domijn kopen!
# Handleiding schrijven! 1 team verwisselen is (meestal) genoeg :)
# password is havenstraat
# Ik mag nu geen roeiers wissen die teams hebben en omgekeerd, dat wordt leuk:(
# En kan teams ook niet leegmaken...




# Controle:
# Bij een lege resource gaat de hele site op zijn gat??
# Controleren of alles is gedefineerd  zoals results die later showen in heats pagina!
# validates laat gedaan in modell en niet nagekeken!
# Gaan alle lastige dingen zoals results op alle (inclusief team) paginas goed?
# results 1.20 + 2.0 is soms 3.21111111
# Gaat rank uitrekenen bij meerdere heats netjes?
# alle links controleren, sterkte!
# controleren of je club.id hebt omgeschreven in .name
# Wat ik  met mentor heb gedaan op club edit pagina met blank?
# alle destroy warning msges wel netjes? ook pop up?
# !!! Velden mogen niet leeg zijn, creeerde net 20 boten :)   en sommige unqieness
#  OEf werken alle notices and errors?

# Wat niet hoeft
# Bij maken team   aantal rowers afhankelijk van type is nog een uitdaging (hoeft niet)
# Als laatste clubs/edit veranderen! (of wel goed zo? wel meer vrijheid voor admin!)
#!!!VRAGEN!!! invoeren boten, boat_ids e.d.apparte pagina admin (lastig met keuze menu!)(params verstuurd welke geedit moet worden, piece of cake!)
# JUST DO IT! Boattype category noemen!! DAT IS EEN BITCH EERST NIEUWE GENEREREN DAN OUDE VERWIJDEREN :(

# Later
# !! uitkijken dat navbar niet op elkaar stapeld dan is de helft niet te zien
# Wel heel cool een navbar die eerst op site zweeft en later onder main navbar plakt, zie bootswatsch
# opmaak:
# responsive
# Small text in h1 header weg bij responsive!











ZzvJeugdwedstrijden::Application.routes.draw do

  # Routes for about:
  root :to => 'about#index'
  get '/about', controller: 'about', action: 'index', as: 'about'

  # Routes for sessions:
  get '/sessions/new' => 'sessions#new', as: 'new_session'
  post '/sessions' => 'sessions#create', as: 'sessions'
  delete '/sessions' => 'sessions#destroy'

  # Routes for the Admin resource:
  # CREATE
  get '/admins/new', controller: 'admins', action: 'new', as: 'new_admin'
  post '/admins', controller: 'admins', action: 'create'

  # READ
  get '/admins', controller: 'admins', action: 'index', as: 'admins'
  get '/admins/:id', controller: 'admins', action: 'show', as: 'admin'

  # UPDATE
  get '/admins/:id/edit', controller: 'admins', action: 'edit', as: 'edit_admin'
  put '/admins/:id', controller: 'admins', action: 'update'

  # DELETE
  delete '/admins/:id', controller: 'admins', action: 'destroy'
  #------------------------------

  # Routes for the Team_classification resource:
  # CREATE
  get '/team_classifications/new', controller: 'team_classifications', action: 'new', as: 'new_team_classification'
  post '/team_classifications', controller: 'team_classifications', action: 'create'

  # READ
  get '/team_classifications', controller: 'team_classifications', action: 'index', as: 'team_classifications'
  get '/team_classifications/:id', controller: 'team_classifications', action: 'show', as: 'team_classification'

  # UPDATE
  get '/team_classifications/:id/edit', controller: 'team_classifications', action: 'edit', as: 'edit_team_classification'
  put '/team_classifications/:id', controller: 'team_classifications', action: 'update'

  # DELETE
  delete '/team_classifications/:id', controller: 'team_classifications', action: 'destroy'
  #------------------------------

  # Routes for the Result resource:
  get '/results/edit', controller: 'results', action: 'edit', as: 'edit_result'

  # CREATE
  get '/results/new', controller: 'results', action: 'new', as: 'new_result'
  post '/results', controller: 'results', action: 'create'

  # READ
  get '/results', controller: 'results', action: 'index', as: 'results'
  get '/results/:id', controller: 'results', action: 'show', as: 'result'

  # UPDATE

  put '/results/:id', controller: 'results', action: 'update'

  # DELETE
  delete '/results/:id', controller: 'results', action: 'destroy'
  #------------------------------

  # Routes for the Team resource:
  # CREATE
  get '/teams/new', controller: 'teams', action: 'new', as: 'new_team'
  post '/teams', controller: 'teams', action: 'create'

  # READ
  get '/teams', controller: 'teams', action: 'index', as: 'teams'
  get '/teams/:id', controller: 'teams', action: 'show', as: 'team'

  # UPDATE
  get '/teams/:id/edit', controller: 'teams', action: 'edit', as: 'edit_team'
  put '/teams/:id', controller: 'teams', action: 'update'

  # DELETE
  delete '/teams/:id', controller: 'teams', action: 'destroy'

  #------------------------------

  # Routes for the Rower_classification resource:
  # CREATE
  get '/rower_classifications/new', controller: 'rower_classifications', action: 'new', as: 'new_rower_classification'
  post '/rower_classifications', controller: 'rower_classifications', action: 'create'

  # READ
  get '/rower_classifications', controller: 'rower_classifications', action: 'index', as: 'rower_classifications'
  get '/rower_classifications/:id', controller: 'rower_classifications', action: 'show', as: 'rower_classification'

  # UPDATE
  get '/rower_classifications/:id/edit', controller: 'rower_classifications', action: 'edit', as: 'edit_rower_classification'
  put '/rower_classifications/:id', controller: 'rower_classifications', action: 'update'

  # DELETE
  delete '/rower_classifications/:id', controller: 'rower_classifications', action: 'destroy'
  #------------------------------

  # Routes for the Rower resource:
  # CREATE
  get '/rowers/new', controller: 'rowers', action: 'new', as: 'new_rower'
  post '/rowers', controller: 'rowers', action: 'create'

  # READ
  get '/rowers', controller: 'rowers', action: 'index', as: 'rowers'
  get '/rowers/:id', controller: 'rowers', action: 'show', as: 'rower'

  # UPDATE
  get '/rowers/:id/edit', controller: 'rowers', action: 'edit', as: 'edit_rower'
  put '/rowers/:id', controller: 'rowers', action: 'update'

  # DELETE
  delete '/rowers/:id', controller: 'rowers', action: 'destroy'
  #------------------------------
  # Routes for the Heat resource:

  get '/heats/edit', controller: 'heats', action: 'edit', as: 'edit_heat'


  # CREATE
  get '/heats/new', controller: 'heats', action: 'new', as: 'new_heat'
  post '/heats', controller: 'heats', action: 'create'

  # READ
  get '/heats', controller: 'heats', action: 'index', as: 'heats'
  get '/heats/:id', controller: 'heats', action: 'show', as: 'heat'

  # UPDATE
  put '/heats/:id', controller: 'heats', action: 'update'

  # DELETE
  delete '/heats/:id', controller: 'heats', action: 'destroy'
  #------------------------------
  # Routes for the Club resource:

  # Teams & Rowers
  get '/clubs/:id/teams', controller: 'clubs', action: 'teams', as: 'club_teams'
  get '/clubs/:id/rowers', controller: 'clubs', action: 'rowers', as: 'club_rowers'

  # CREATE
  get '/clubs/new', controller: 'clubs', action: 'new', as: 'new_club'
  post '/clubs', controller: 'clubs', action: 'create'

  # READ
  get '/clubs', controller: 'clubs', action: 'index', as: 'clubs'
  get '/clubs/:id', controller: 'clubs', action: 'show', as: 'club'

  # UPDATE
  get '/clubs/:id/edit', controller: 'clubs', action: 'edit', as: 'edit_club'
  put '/clubs/:id', controller: 'clubs', action: 'update'

  # DELETE
  delete '/clubs/:id', controller: 'clubs', action: 'destroy'
  #------------------------------

  # Routes for the Boat_type resource:
  # CREATE
  get '/boat_types/new', controller: 'boat_types', action: 'new', as: 'new_boat_type'
  post '/boat_types', controller: 'boat_types', action: 'create'

  # READ
  get '/boat_types', controller: 'boat_types', action: 'index', as: 'boat_types'
  get '/boat_types/:id', controller: 'boat_types', action: 'show', as: 'boat_type'

  # UPDATE
  get '/boat_types/:id/edit', controller: 'boat_types', action: 'edit', as: 'edit_boat_type'
  put '/boat_types/:id', controller: 'boat_types', action: 'update'

  # DELETE
  delete '/boat_types/:id', controller: 'boat_types', action: 'destroy'

  # Calculate Rankings
  get '/boat_types/:id/calculaterank', controller: 'boat_types', action: 'calculaterank', as: 'calculaterank'
  #------------------------------

  # Routes for the Boat resource:
  # CREATE
  get '/boats/new', controller: 'boats', action: 'new', as: 'new_boat'
  post '/boats', controller: 'boats', action: 'create'

  # READ
  get '/boats', controller: 'boats', action: 'index', as: 'boats'
  get '/boats/:id', controller: 'boats', action: 'show', as: 'boat'

  # UPDATE
  get '/boats/:id/edit', controller: 'boats', action: 'edit', as: 'edit_boat'
  put '/boats/:id', controller: 'boats', action: 'update'

  # DELETE
  delete '/boats/:id', controller: 'boats', action: 'destroy'
  #------------------------------
end

app/models/heat.rb
class Heat < ActiveRecord::Base
  has_many :team_classifications
  has_many :boats, :through => :team_classifications
  has_many :teams, :through => :team_classifications
  has_many :results

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/heats_controller.rb
class HeatsController < ApplicationController
before_filter :authorize_user, except: [:index, :show]

before_filter :heats_with_results_or_assigned_teams?, only: [:destroy]


def heats_with_results_or_assigned_teams?
        @heat = Heat.find_by_id(params[:id])
        @heat.errors.add(:base, "Can not delete heat with results or teams assigned") unless @heat.results.count == 0 && @heat.team_classifications.count == 0
        unless @heat.errors.blank?
          flash[:error] = @heat.errors.full_messages
          redirect_to :back
        end

end



  def index
    @heats = Heat.all.sort! { |a,b| a.name.to_i <=> b.name.to_i }
    @boat_types = BoatType.all
    @results = Result.all

    respond_to do |format|
      format.html
      format.xls
    end

  end

  def show
    @heat = Heat.find_by_id(params[:id])
  end

  def new
    @heat = Heat.new
  end

  def create
    @heat = Heat.new
    @heat.name = params[:name]

    if @heat.save
            redirect_to edit_heat_url, notice: "Heat created successfully"
          else
      flash[:error] = @heat.errors.full_messages
      redirect_to :back
    end
  end

  def edit
    @boat_types = BoatType.all
    @heats = Heat.all.sort! { |a,b| a.name.to_i <=> b.name.to_i }
    @heat = Heat.find_by_id(params[:id])
  end

  def update
    @heat = Heat.find_by_id(params[:id])
    @heat.name = params[:name]

    if @heat.save
            redirect_to :back, notice: "Heat updated successfully"
          else
      flash[:error] = @heat.errors.full_messages
      redirect_to :back
    end
  end

  def destroy
    @heat = Heat.find_by_id(params[:id])
    @heat.destroy
    redirect_to :back, notice: "Head removed successfully"

  end
end

app/views/heats/edit.html.erb
<div class="page-header">
  <h1>Heats <small>when do you race?</small></h1>
</div>

    <% @boat_types.each do |boat_type| %>
      <% if (boat_type.teams.map{|x| x.team_classifications.count}).uniq.count > 1 %>
        <div class="alert alert-error">
          <h4>Warning</h4>
          <%= boat_type.name %>: Some teams are currently classified <%= (boat_type.teams.map{|x| x.team_classifications.count}).uniq[0]%> times, while others are classified <%= (boat_type.teams.map{|x| x.team_classifications.count}).uniq[1]%> times. Please adjust.
          <p><% boat_type.teams.each do |team| %>
            <%= link_to team.name, team_url(team) %>(<%= team.team_classifications.count%>x)
          <% end %><p>
        </div>
      <% end %>
    <% end %>


<p><%= link_to 'Add a New Heat', new_heat_url, :class => "btn btn-success" %></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Heat</th>
      <th>Lane 1</th>
      <th>Lane 2</th>
      <th>lane 3</th>
      <th>Lane 4</th>
    </tr>
  </thead>

  <tbody>
  <% @heats.each do |heat| %>
    <tr>
      <td><%= heat.name %><br><%= link_to 'Destroy Heat', heat_url(heat), method: 'delete', data: { confirm: "Do you really want to delete this heat?" }, :class => "btn btn-danger"  %></td>
        <% heat.team_classifications.each do |team_classification|%>
        <td>
            <%= form_tag(team_classification_url(TeamClassification.find_by_heat_id_and_team_id(heat.id,team_classification.team.id)), method: 'put') do %>

            <%= select_tag(:team_id, options_from_collection_for_select(Team.all, :id, :name, team_classification.team.id)) %>

            <%= select_tag(:boat_id, options_from_collection_for_select(Boat.all, :id, :name, team_classification.boat.id)) %>

            <%= hidden_field_tag(:heat_id, team_classification.heat.id) %>

            <%= submit_tag "Update", :class => "btn btn-warning"  %>
            <%= link_to 'Destroy', team_classification_url(TeamClassification.find_by_heat_id_and_team_id(team_classification.heat.id,team_classification.team.id)), method: 'delete', data: { confirm: "Do you really want to delete this team classification?" }, :class => "btn btn-danger"  %>
          <% end %>
        </td>
        <% end %>
        <% (4-heat.teams.each.count).times do%>
        <td>
            currently empty
            <%= form_tag(team_classifications_url, method: 'post') do %>

            <%= select_tag(:team_id, options_from_collection_for_select(Team.all, :id, :name)) %>

            <%= select_tag(:boat_id, options_from_collection_for_select(Boat.all, :id, :name)) %>

            <%= hidden_field_tag(:heat_id, heat.id) %>

            <%= submit_tag "Create", :class => "btn btn-success"  %>
          <% end %>
        </td>
        <% end %>
    </tr>




  <% end %>
  </tbody>
</table>

app/views/heats/index.html.erb
<div class="page-header">
  <h1>Heats <small>when do you race?</small></h1>
</div>

<%= link_to 'Show results per category', boat_types_url, :class => "btn btn-inverse"  %>
<%= link_to 'Download to Excel', heats_url(format: "xls"), :class => "btn btn-inverse" %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Heat</th>
      <th>Lane 1</th>
      <th>Lane 2</th>
      <th>Lane 3</th>
      <th>Lane 4</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @heats.each do |heat| %>
    <tr>
      <td><%= heat.name %></td>

        <% heat.team_classifications.each do |team_classification|%>
          <td>
            <%= "#{team_classification.team.name} (#{team_classification.team.rowers[0].name})"%>

            <% if Result.exists?(:heat_id => team_classification.heat.id, :team_id => team_classification.team.id) %>

              <p class="text-info"><strong>
              Laptime =
              <%=Result.find_by_heat_id_and_team_id(team_classification.heat.id,team_classification.team.id).laptime %><br>

              Rank =
              <%=Result.find_by_heat_id_and_team_id(team_classification.heat.id,team_classification.team.id).rank %>
              </strong></p>

            <% else %>
              <p><%= team_classification.boat.name %><p>
            <% end %>
          </td>
        <% end %>

        <% (4-heat.teams.each.count).times do%>
        <td></td>
        <% end %>
        <td>
          <%= link_to 'Show all rowers', heat_url(heat), :class => "btn btn-inverse"  %>
        </td>
    </tr>

  <% end %>
  </tbody>
</table>

app/views/heats/index.xls.erb
<table border=1>
    <tr>
      <th>Heat</th>
      <th>Lane 1</th>
      <th>Lane 2</th>
      <th>Lane 3</th>
      <th>Lane 4</th>
    </tr>
  <% @heats.each do |heat| %>
    <tr>
      <td><%= heat.name %></td>

        <% heat.team_classifications.each do |team_classification|%>
          <td>
            <%= "#{team_classification.team.name} (#{team_classification.team.rowers[0].name})"%>

            <% if Result.exists?(:heat_id => team_classification.heat.id, :team_id => team_classification.team.id) %>

              <p class="text-info"><strong>
              Laptime =
              <%=Result.find_by_heat_id_and_team_id(team_classification.heat.id,team_classification.team.id).laptime %><br>

              Rank =
              <%=Result.find_by_heat_id_and_team_id(team_classification.heat.id,team_classification.team.id).rank %>
              </strong></p>

            <% else %>
              <p><%= team_classification.boat.name %><p>
            <% end %>
          </td>
        <% end %>

        <% (4-heat.teams.each.count).times do%>
        <td></td>
        <% end %>
    </tr>
  <% end %>
</table>

app/views/heats/new.html.erb
<div class="page-header">
  <h1>Heats <small>when do you race?</small></h1>
</div>

<h3>It is suggested to use estimated start times as names</h3>
<%= form_tag(heats_url, method: 'post') do %>


  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name %>
  </div>


  <div>
    <%= submit_tag "Create Heat" %>
  </div>
<% end %>

app/views/heats/show.html.erb
<div class="page-header">
  <h1><%=@heat.name.capitalize %> <small>when do you race?</small></h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
        <% @heat.teams.each do |team|%>
        <th><%= team.name %></th>
        <% end %>
        <% (4-@heat.teams.each.count).times do%>
        <th></th>
        <% end %>
    </tr>
  </thead>

  <tbody>
    <tr>
        <% @heat.boats.each do |boat|%>
        <td><%= boat.name %></td>
        <% end %>
        <% (4-@heat.boats.each.count).times do%>
        <td></td>
        <% end %>
    </tr>
    <tr>
      <% @heat.teams.each do |team|%>
        <td>
          <% team.rowers.each do |rower|%>
            <p><%= rower.name %></p>
          <% end %>
        <% end %>
        </td>
        <% (4-@heat.teams.each.count).times do%>
        <td></td>
        <% end %>
    </tr>
  </tbody>
</table>